using System.Reflection;
[assembly: AssemblyTitle("Diamond Lands")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("Diamond Lands")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2015-2106")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.2")]
